package me.ifmo.ticket_service.web.request;

import io.swagger.v3.oas.annotations.media.Schema;

import jakarta.validation.constraints.NotEmpty;
import jakarta.validation.constraints.NotNull;
import me.ifmo.ticket_service.domain.enums.EventType;

import java.time.ZonedDateTime;

@Schema(description = "Event to create. The id is generated by the server.")
public record EventCreateRequest(
        @NotEmpty
        @Schema(description = "Non-empty event name.", example = "Concert", minLength = 1, requiredMode = Schema.RequiredMode.REQUIRED)
        String name,

        @Schema(description = "Optional ISO-8601 date-time with an offset. Omission or null clears it in PUT.", example = "2026-12-01T18:00:00Z", format = "date-time", types = {"string", "null"}, requiredMode = Schema.RequiredMode.NOT_REQUIRED)
        ZonedDateTime date,

        @NotNull
        @Schema(description = "Event type.", example = "CONCERT", requiredMode = Schema.RequiredMode.REQUIRED)
        EventType type
) {
}
